stages:
  - deploy

deploy_backend:
  stage: deploy
  only:
    - main

  script:
    - |

      cd ~/ug_hf_3/Backend/FastAPI

      echo "==> Updating repo"
      git pull origin main

      echo "==> Stopping old service"
      sudo systemctl stop stock-ai-backend.service || true
      sudo systemctl disable stock-ai-backend.service || true
      sudo rm -f /etc/systemd/system/stock-ai-backend.service
      sudo systemctl daemon-reload

      echo "==> Removing old container"
      sudo podman rm -f stock-ai-backend || true

      echo "==> Building new image"
      sudo podman build -t myfastapi .

      echo "==> Starting container (host network)"
      sudo podman run -d --name stock-ai-backend --env-file .env -p 8080:8080 myfastapi

      echo "==> Generating systemd service"
      sudo podman generate systemd --name stock-ai-backend \
        | sudo tee /etc/systemd/system/stock-ai-backend.service >/dev/null

      sudo systemctl daemon-reload
      sudo systemctl enable stock-ai-backend.service
      sudo systemctl start stock-ai-backend.service

      echo "Deploy successful"
      EOF
