stages:
  - fastapibuild

fastapi-build:            
  stage: fastapibuild
  tags:
    - main_backend
  script:
    - cd Backend
    - cd FastAPI        
    - systemctl stop stock-ai-backend.service
    - systemctl disable stock-ai-backend.service
    - rm /etc/systemd/system/stock-ai-backend.service
    - systemctl daemon-reload
    - podman rm -f stock-ai-backend || true
    - podman rmi myfastapi || true
    - podman system prune -f
    - podman build -t myfastapi .
    - podman run -d --name stock-ai-backend --env-file .env -p 8080:8080 myfastapi
    - podman generate systemd --name stock-ai-backend | sudo tee /etc/systemd/system/stock-ai-backend.service
    - systemctl daemon-reload
    - systemctl enable stock-ai-backend.service
    - systemctl start stock-ai-backend.service
  only:
    refs:
      - main
    changes: 
      - Backend/**/*